### ISSUE TITLE
Transfer limit for ETH and token transfers

### ISSUE THREAD

**Issue by GnosisEcosystemFund** [GnosisEcosystemFund/Gnosis-Bounties-#1]
### Background
The Gnosis Safe as multi-signature wallet requires all transactions to be signed by a predefined (sub)set of owners. In some use cases, it is desirable that only a single owner or a smaller subset allowed to make transfers up to a certain limit. These will be realized via modules within the [Gnosis Safe smart contracts](https://github.com/gnosis/safe-contracts/). A simple implementation of a daily limit module can be found [here](https://github.com/gnosis/safe-contracts/blob/development/contracts/modules/DailyLimitModule.sol).
### Task
Please write a general transfer limit module (or several thereof) for the Gnosis Safe.

**Acceptance criteria**

- The solution is implemented as Gnosis Safe smart contract module in Solidity. 
- A user can specify the time frame of the transfer limit, i.e. the point in time when it gets reset to 0
  -  The limit can reset daily or weekly on the beginning of the time frame or be “rolling”, i.e. always consider the exact last 24h or last 7 days.
- A user can specify how many owners need to confirm the transfer first. (Minimum: 1, maximum: global confirmation threshold of the Safe - 1)
- It is possible to set a transfer limit for ETH and each token separately
- It is possible to set a global transfer limit in ETH that considers also token transfers (ETH <> token is converted via a ticker.)
  - Please use the [DutchX](https://dutchx.readthedocs.io/en/latest/) as price oracle
- The Safe has the feature to pay for transaction fees with funds from within the contract. The submitter of the transaction gets refunded as part of the transaction (cf. [smart contract](https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L66) and [docs](https://gnosis-safe.readthedocs.io/en/latest/contracts/meta_tx.html)) The transfer limit module needs to have the same feature.
- The user can specify an optional non-owner address that is also authorized to perform transactions up to the transfer limit.
- It is possible to set a global transfer limit in fiat currency.
  - Please use the [DutchX](https://dutchx.readthedocs.io/en/latest/) as price oracle (1USD = 1DAI)
- All smart contracts have 100% test coverage with solidity-coverage
- All public methods have netspecs
- Linters are applied (Solium or Solhint)
- Readme with setup instructions and explanations for implementation details
- All code (Variables, function names, comments) is in English

### Payout: 
200 GNO
Additional GNO can be tipped according to the level of technical implementation

### Others
Read our [documentation](https://gnosis-safe.readthedocs.io/en/latest/index.html) to get started.
Contact us via [Gitter](https://gitter.im/gnosis/Safe) in case you need support or have questions.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 GNO   attached to it as part of the Gnosis fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $54,694.37 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 years, 8 months ago.
Please review their action plans below:


**1) [s1na](https://gitcoin.co/s1na) has been approved to start work.**

I will try to implement the spec, drawing upon my experience of developing another Gnosis Safe [module](https://github.com/planet-ethereum/ethbase/blob/master/contracts/SafeModule.sol).
**2) [phabc](https://gitcoin.co/phabc) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/gnosisecosystemfund/gnosis-bounties-/1/1624?mutate_worker_action=approve&worker=phabc) | [reject worker](https://gitcoin.co/issue/gnosisecosystemfund/gnosis-bounties-/1/1624?mutate_worker_action=reject&worker=phabc))_.**

I believe I have already a good understanding of how the Gnosis Safe works and find most criteria manageable. I would start by building the general payment limit based on token amounts and then add supports for fiat limit via the DutchX platform, which I believe is the main piece that will need to read more about.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/gnosisecosystemfund/gnosis-bounties-/1/1624).

**Comment by frankchen07** [comment]
hello @GnosisEcosystemFund - Frank from Gitcoin here - you have workers waiting for your approval! :)

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=1) | [3 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=3) | [5 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=5) | [10 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=10) | [100 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=100)

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=1) | [3 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=3) | [5 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=5) | [10 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=10) | [100 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=100)

**Comment by s1na** [comment]
Hey @gitcoinbot, yes, I was at devcon and I will be starting to work on this only from now. I'll make a WIP PR in [safe-contracts](https://github.com/gnosis/safe-contracts) soon.

**Comment by GnosisEcosystemFund** [comment]
@s1na  I snoozed the Gitcoinbot you should have a few days for working on the bounty. 
great to have you on board, looking forward to your implementation. Feel free to reach out to us if you have more questions.

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=1) | [3 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=3) | [5 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=5) | [10 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=10) | [100 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=100)

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=1) | [3 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=3) | [5 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=5) | [10 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=10) | [100 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=100)

**Comment by s1na** [comment]
@gitcoinbot Yes, here's the [PR](https://github.com/gnosis/safe-contracts/pull/75) :)

**Comment by spm32** [comment]
Thanks @s1na!

**Comment by gitcoinbot** [comment]
@s1na Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=1) | [3 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=3) | [5 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=5) | [10 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=10) | [100 days](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624?snooze=100)

**Comment by s1na** [comment]
During this week I will try to address the [comments](https://github.com/gnosis/safe-modules/pull/2).

**Comment by MareenG** [comment]
@s1na no worries it was the Gitcoinbot. I will snooze him for a few more days :)

**Comment by lazaridiscom** [comment]
Ping...

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 100.00000  GNO (2209.0 USD @ $22.09/GNO) has been granted to @s1na for this issue from @GnosisEcosystemFund. ⚡️ 

Nice work @s1na! Your tip has automatically been deposited in the ETH address we have on file.

 * $105915.22 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This Bounty has been completed.__

Additional Tips for this Bounty:
* GnosisEcosystemFund tipped 100.0000 GNO worth 2209.0 USD to s1na.

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/GnosisEcosystemFund/Gnosis-Bounties-/1/1624)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $105,915.22 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
